# Site Settings
title: Korin
description: Developer and Photographer from Europe
author: Korin
email: korin@itskorin.online
baseurl: ""
url: "https://itskorin.online"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

seo:
  description: Developer and Photographer from Europe
  author: Korin

navigation:
  - title: Games
    url: /#games
  - title: Photos
    url: /#photos
  - title: About Me
    url: /#about
  - title: Contact
    url: /#contact

social:
  twitter: ItsKowwin
  github: ItsKorin
